# create this file if you need to configure anything
maker:
  # tell MakerBundle that all of your classes lives in an
  # OtusHw namespace, instead of the default App
  # (e.g. OtusHw\Entity\Article, OtusHw\Command\MyCommand, etc)
  root_namespace: 'OtusHw'
