version: '3.7'
services:
  db_mysql:
    image: mysql:5.7
    volumes:
      - ./db_mysql_data:/var/lib/mysql
    restart: always
    container_name: otus-hw-db
    # Формат записи портов: HOST_PORT:CONTAINER_PORT
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=otus_hw
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=qwe
    networks:
      hostnet:

  web-app:
    build:
      context: ./../
      dockerfile: docker/Dockerfile
    container_name: otus-hw-web-app
    working_dir: /app
    volumes:
      - ./../:/app
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    sysctls:
      net.core.somaxconn: 1024
    ports:
      - "2280:22"
      - "8080:80"
      - "8000:8000"
    networks:
      hostnet:

  grafana:
    image: grafana/grafana:latest
    container_name: otus-hw-grafana
    volumes:
      - ./grafana_data/:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      hostnet:

  influxdb:
    image: influxdb:1.8
    container_name: otus-hw-influxdb
    volumes:
      - ./influxdb_data/:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=jmeterresults
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=root_asd_098
      - INFLUXDB_USER=jmeteruser
      - INFLUXDB_USER_PASSWORD=123qwe
    ports:
      - "8086:8086"
    networks:
      hostnet:

  zabbix-server:
    image: zabbix/zabbix-appliance:alpine-trunk
    container_name: otus-hw-zabbix-server
    ports:
      - "8001:80"
      - "10051:10051"
    volumes:
      - ./db_zabbix_mysql_data:/var/lib/mysql
    networks:
      hostnet:

volumes:
  db_mysql_data:
  grafana_data:
  influxdb_data:
  db_zabbix_mysql_data:

networks:
  hostnet:
    name: otus-hw-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
